version: '3'
services:
  apache:
      build: .
      # image: php:7.2-apache
      volumes:
        - ./apache2/apache2.conf:/etc/apache2/sites-enabled/000-default.conf
        - ./apache2/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
        - ./webapp/src:/var/www/html
        - ./apache2/apache-selfsigned.crt:/etc/ssl/certs/apache-selfsigned.crt
        - ./apache2/apache-selfsigned.key:/etc/ssl/private/apache-selfsigned.key
      restart: always
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - db

  db:
      image: mysql:latest
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql
        - ./mysql/sql:/docker-entrypoint-initdb.d
        - ./mysql/mysql.cnf:/etc/mysql/my.cnf
      environment:
        MYSQL_USER: user
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: calendar
        TZ: 'Asia/Tokyo'
      restart: always

volumes: 
    db_data: 
